FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
COPY EnrollmentMS/Presentation/EnrollmentMS.API.csproj ./Presentation/
RUN dotnet restore

COPY . ./
RUN dotnet publish EnrollmentMS/Presentation/EnrollmentMS.API.csproj -c Release -o /out
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
COPY --from=build /out .
ENTRYPOINT ["dotnet", "EnrollmentMS.API.dll"]
